### ISSUE TITLE
Spike Istio Global Rate Limit for Sidecar

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [zufardhiyaulhaq/journals#1]
AC:
- find out how to make global rate limit working on sidecar

**Comment by zufardhiyaulhaq** [comment]
since we cannot modify sidecar inbound routing configuration easily, the rate limit for sidecar is very limited. this will rate limit any request (header + path)

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  labels:
    istio/version: "1.9"
  name: echo-redis-1.9
  namespace: default
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
      proxy:
        proxyVersion: ^1\.9.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.ratelimit
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
          domain: public-gateway
          failure_mode_deny: false
          rate_limit_service:
            grpc_service:
              envoy_grpc:
                cluster_name: public-gateway
              timeout: 10s
            transport_api_version: V3
          timeout: 10s
  - applyTo: CLUSTER
    match:
      cluster:
        service: public-gateway-ratelimit-service.istio-system.svc
      context: SIDECAR_INBOUND
      proxy:
        proxyVersion: ^1\.9.*
    patch:
      operation: ADD
      value:
        connect_timeout: 10s
        http2_protocol_options: {}
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: public-gateway
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: public-gateway-ratelimit-service.istio-system.svc
                    port_value: 8081
        name: public-gateway
        type: STRICT_DNS
  workloadSelector:
    labels:
      app: echo-redis
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  labels:
    istio/version: "1.9"
  name: echo-redis-http-8080-1.9
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      proxy:
        proxyVersion: ^1\.9.*
      routeConfiguration:
        vhost:
          name: inbound|http|8080
          route:
            action: ANY
    patch:
      operation: MERGE
      value:
        route:
          rate_limits:
          - actions:
            - request_headers:
                descriptor_key: method
                header_name: :method
            - request_headers:
                descriptor_key: path
                header_name: :path
  workloadSelector:
    labels:
      app: echo-redis
```
